# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=50, verbose_name='Name')),
                ('location', models.CharField(max_length=50, verbose_name='Artist')),
                ('image', models.URLField(verbose_name='Url')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('artist', models.CharField(max_length=50, verbose_name='Artist')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('artist', models.CharField(max_length=50, verbose_name='Artist')),
                ('url', models.URLField(verbose_name='Url')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('shots', models.CharField(default='', max_length=200, verbose_name='Shots')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
        ),
    ]
