# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='Description'),
        ),
    ]
