# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20171021_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='imageURL',
            new_name='imageurl',
        ),
    ]
