# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20171029_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='desc1',
            field=models.TextField(default='', verbose_name='desc1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='desc2',
            field=models.TextField(default='', verbose_name='desc2'),
            preserve_default=False,
        ),
    ]
