# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_artist_spotifyuri'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='setList',
            field=models.TextField(default='', verbose_name='setList'),
            preserve_default=False,
        ),
    ]
