# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_video_setlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='setListTime',
            field=models.TextField(default='', verbose_name='setListTime'),
            preserve_default=False,
        ),
    ]
