# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_video_setlisttime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surahValue', models.CharField(max_length=50, verbose_name='surahValue')),
                ('surahName', models.CharField(max_length=50, verbose_name='surahName')),
            ],
        ),
    ]
