# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20171107_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectID', models.IntegerField(verbose_name='objectID')),
                ('rangeStart', models.IntegerField(verbose_name='rangeStart')),
                ('rangeEnd', models.IntegerField(verbose_name='rangeEnd')),
                ('explanation', models.TextField(verbose_name='explanation')),
                ('translation', models.TextField(verbose_name='translation')),
                ('surah', models.CharField(max_length=100, verbose_name='surah')),
                ('quranText', models.CharField(max_length=100, verbose_name='quranText')),
                ('connectPrev', models.CharField(max_length=3, verbose_name='connectPrev')),
            ],
        ),
    ]
