# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_translations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translations',
            name='quranText',
            field=models.TextField(verbose_name='quranText'),
        ),
    ]
