# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_auto_20171117_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surahdetailed',
            name='surahValue',
        ),
        migrations.AddField(
            model_name='surahdetailed',
            name='surahLabel',
            field=models.TextField(default='', verbose_name='surahLabel'),
            preserve_default=False,
        ),
    ]
