# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_clean_user_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='def', max_length=50, verbose_name='username'),
            preserve_default=False,
        ),
    ]
