# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='dateText',
            field=models.CharField(default='TBA', max_length=50, verbose_name='dateText'),
            preserve_default=False,
        ),
    ]
