# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_banner_datetext'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.CharField(default='', max_length=250, verbose_name='description'),
            preserve_default=False,
        ),
    ]
