# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_banner_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='description'),
        ),
    ]
