# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_videoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='upvotes',
            field=models.IntegerField(default=1, verbose_name='upvotes'),
            preserve_default=False,
        ),
    ]
